FROM microsoft/dotnet
MAINTAINER Chris Small

RUN mkdir /app
COPY ./bin/Release/netcoreapp2.0/publish /app
WORKDIR /app

ENTRYPOINT ["dotnet", "/app/Nooptime.Web.dll"]

# ASP.NET Core: make sure views use the production versions
ENV ASPNETCORE_ENVIRONMENT="Production"

# ASP.NET Core: Kestrel should listen on all IPs
ENV ASPNETCORE_URLS="http://0.0.0.0:5000"

# Postgres database connection string
ENV Database:ConnectionString=""
